# Base configs
baseurl: "https://samueldbiggs1-cyber.github.io/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sam Biggs"
subtitle: "See the world through my eyes!"
author: "Sam Biggs"
header:
 title: "Photography"
 subtitle: "by Sam Biggs"
footer:
 name: "Hey there, my name is Sam"
 bio: "I am a software developer and a tech aficionado. Love making teeny tiny apps solving tiny problems in life and now learning photography."

social_urls:
  twitter: "https://www.twitter.com/sambiggs"
  instagram: "https://www.instagram.com/sambiggs"
  dribbble: "https://dribbble.com/sambiggs"
  linkedin: "https://in.linkedin.com/in/sambiggs"
  github: "https://www.github.com/sambiggs"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
